spring:
  shell:
#  .command.help.commands-template
    theme:
      name: "amvera-theme"
    command:
      help:
        commands-template: "classpath:template/help-commands-custom.stg"
        command-template: "classpath:template/help-command-custom.stg"
      version:
        enabled: false
      history:
        enabled: false
      stacktrace:
        enabled: false
      clear:
        enabled: false
      script:
        enabled: false
  main:
    banner-mode: "off"
shell:
  out:
    info: "CYAN"
    success: "GREEN"
    warning: "YELLOW"
    error: "RED"
logging:
  level:
    root: off
