spring:
  shell:
#    help:
#      long-names: help
#      short-names: h
#      command: help
    command:
      version:
        enabled: false
      history:
        enabled: false
      stacktrace:
        enabled: false
      clear:
        enabled: false
      script:
        enabled: false
  main:
    banner-mode: "off"
shell:
  out:
    info: "CYAN"
    success: "GREEN"
    warning: "YELLOW"
    error: "RED"
logging:
  level:
    root: off
