spring:
  profiles:
    active: staging

amvera:
  keycloak-client: "amvera-cli"
  #  keycloak-client: "amvera-web"
  version: ^project.version^
endpoints:
  logs: https://notifications.amvera.ru/logs
  projects: https://api.amvera.ru/projectss
  configurations: https://api.amvera.ru/configurations
  balance: https://api.amvera.ru/balancelkl
  env: https://api.amvera.ru/env
  tariff: https://api.amvera.ru/tariff
  token: https://id.amvera.ru/auth/realms/amvera/protocol/openid-connect/token
  user: https://id.amvera.ru/auth/realms/amvera/account/
  logout: https://id.amvera.ru/auth/realms/amvera/protocol/openid-connect/revoke
