spring:
  shell:
    interactive:
      enabled: false
    theme:
      name: "amvera-theme"
    command:
      version:
        enabled: false
      history:
        enabled: false
      stacktrace:
        enabled: false
      clear:
        enabled: false
      script:
        enabled: false
      quit:
        enabled: false
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: false
shell:
  out:
    info: "CYAN"
    success: "GREEN"
    warning: "YELLOW"
    error: "RED"
#logging:
#  level:
#    root: off

amvera:
  keycloak-client: "amvera-cli"
  version: ^project.version^
endpoints:
  logs: https://notifications.amvera.ru/logs
  projects: https://api.amvera.ru/projects
  marketplace: https://api.amvera.ru/marketplace
  postgresql: https://api.amvera.ru/postgresql
  configurations: https://api.amvera.ru/configurations
  balance: https://api.amvera.ru/balance
  domain: https://api.amvera.ru/domain
  env: https://api.amvera.ru/env
  tariff: https://api.amvera.ru/tariff
  keycloak: https://id.amvera.ru/auth/realms/amvera