name: Build Native CLI and Create Release

on:
  push:
    tags:
      - 'v*'  # Триггер по тегу, например: v0.9.6

jobs:
  build:
    name: Build native binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: amvera-linux
            image_name: amvera-linux
          - os: windows-latest
            artifact_name: amvera-windows.exe
            image_name: amvera-windows
          - os: macos-latest
            artifact_name: amvera-macos-x64
            image_name: amvera-macos-x64
          - os: macos-14
            artifact_name: amvera-macos-arm64
            image_name: amvera-macos-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image: true

      - name: Build native image
        run: ./mvnw clean package -Pnative -DskipTests -Dnative.imageName=${{ matrix.image_name }}

      - name: Rename artifact
        run: |
          mv target/${{ matrix.image_name }} ${{ matrix.artifact_name }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: artifacts/**/*  # Загружаем всё
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
